/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    AppHeader: typeof import('./components/layout/AppHeader.vue')['default']
    AppSidebar: typeof import('./components/layout/AppSidebar.vue')['default']
    AppTabBar: typeof import('./components/layout/AppTabBar.vue')['default']
    EmptyState: typeof import('./components/common/EmptyState.vue')['default']
    GlassCard: typeof import('./components/common/GlassCard.vue')['default']
    LoadingSpinner: typeof import('./components/common/LoadingSpinner.vue')['default']
    MediaCard: typeof import('./components/common/MediaCard.vue')['default']
    PageTitle: typeof import('./components/layout/PageTitle.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchInput: typeof import('./components/common/SearchInput.vue')['default']
    Skeleton: typeof import('./components/common/Skeleton.vue')['default']
    StatCard: typeof import('./components/common/StatCard.vue')['default']
  }
}
